# Generated by Django 3.1.7 on 2021-04-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetbrains_vk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='date',
            field=models.DateField(),
        ),
    ]
